### ISSUE TITLE
Creación de Branches

### ISSUE THREAD

**Issue by santiagocarrilloT** [santiagocarrilloT/MobileAppDevelop#2]
Cada integrante creará una rama donde podrá realizar cada uno de sus cambios, el nombre de dicha rama se realizará con la palabra "develop" seguido de un número, como por ejemplo "develop1" (este nombre está asignado).
- Luego de la creación dejar un comentario donde se confirme la realización de la misma.

**Comment by Edwar-Forero** [comment]
Ya cree mi rama, con el nombre de developE

**Comment by J-E-Calderon** [comment]
Ya cree mi rama, con el nombre de developJ

**Comment by santiagocarrilloT** [comment]
Esta tarea ha sido completada con éxito
